<?php

/**
 * @file
 * An Islandora viewer module using Recline.js
 */
 
/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_reclinejs_islandora_viewer_info() {
  return array(
    'islandora_reclinejs' => array(
      'label' => t('recline.js player'),
      'description' => t('recline.js for tabular data.'),
      'callback' => 'islandora_reclinejs_callback',
      'mimetype' => array('text/csv'),
      #'configuration' => 'admin/islandora/islandora_viewers/reclinejs',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_reclinejs_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_reclinejs' => array(
      'template' => 'theme/islandora-reclinejs',
      'variables' => array('object' => NULL, 'params' => NULL),
    ),
  );
}

/**
 * Callback function to the tabular viewer
 *
 * @param array $params
 *   Array with configuration info for the tabular.
 */
function islandora_reclinejs_callback($params = array()) {
  return theme('islandora_reclinejs', array('params' => $params));
}

/**
 * Implements hook_preprocess().
 */
function islandora_reclinejs_preprocess_islandora_reclinejs(&$variables) {
  $recline_library_path = libraries_get_path('recline');
  $mustache_library_path = libraries_get_path('mustache.js');
  $underscore_library_path = libraries_get_path('underscore');
  $backbone_library_path = libraries_get_path('backbone');
  $module_path = drupal_get_path('module', 'islandora_reclinejs');
  
  $params = $variables['params'];
  
  drupal_add_js(array(
      'islandoraReclineJS' => array(
        'resourceUri' => $params['url'],
      ),
    ),'setting');
  
  drupal_add_js($mustache_library_path . "/mustache.js", array('weight' => -7));
  drupal_add_js($underscore_library_path . "/underscore.js", array('weight' => -6));
  drupal_add_js($backbone_library_path . "/backbone.js", array('weight' => -5));
  drupal_add_js($recline_library_path . "/csv.js", array('weight' => -4));
  drupal_add_js($recline_library_path . "/recline.js", array('weight' => -3));
  drupal_add_js($module_path . "/js/main.js", array('weight' => -2));
  drupal_add_css("$module_path/css/islandora_recline.theme.css");
}
